# Generated by Django 5.1.1 on 2024-10-08 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chais')),
                ('size', models.CharField(choices=[('SM', 'SMALL'), ('MD', 'MEDIUM'), ('LG', 'LARGE')], max_length=2)),
                ('type', models.CharField(choices=[('PL', 'PLAIN'), ('MS', 'MASALA'), ('GG', 'GINGER'), ('GR', 'GREEN')], max_length=2)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
