# Generated by Django 5.1.1 on 2024-10-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='size',
            field=models.CharField(choices=[('SM', 'SMALL'), ('MD', 'MEDIUM')], max_length=2),
        ),
    ]
