# Generated by Django 5.1.1 on 2024-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0002_alter_chaivariety_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default='Description yet to be added.', max_length=250),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=5),
        ),
    ]
