# Generated by Django 5.1.1 on 2024-10-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai_app', '0004_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chai_variety',
            new_name='chai_varieties',
        ),
    ]
